### ISSUE TITLE
Projet : C'est beau

### ISSUE THREAD

**Issue by ghost** [DeuxHuitHuit/www-issues#1]
Good job les boys (and girls?).

J'ai remarqué un typo :

Solution
Laisser rayonner la personnalité
Un place importante a été accordée à la personnalité des artisans. Il est primordial de conférer à chaque objet, toute l’attention qu’il mérite.

"Un place" devrait plutôt être "Une place".

Keep up the good work!

**Comment by PascalPiche** [comment]
Merci, problème résolu :)

**Comment by nitriques** [comment]
Merci @fredaudet :)
