### ISSUE TITLE
Blank Message Sent

### ISSUE THREAD

**Issue by jemimaabu** [DeuxHuitHuit/www-issues#2]
I sent a sample message of "Hello" and received the "You did not specify how we could reach you." error message and the "Send anyway" button.
Then I cleared everything in the textbox and clicked Send anyway and the message sent.
Does this mean the blank message was the delivered or the previously typed message was the one sent?

**Comment by alexleduc** [comment]
Hey thank you very much Jemimaabu,
You just broke the whole machine ;)
Yes, we received your blank message. 
I not 100% shure but i guess this is the first time someone send a blank message in 5 years.
Come in the office if you come in Montreal, we will give you your price lol ;)

Have a great day!

**Comment by jemimaabu** [comment]
Lol, I live to break things.
Sure, if I'm ever in Montreal, I'll hold you to that.
All the best.
